---
- name: Copy dir config file
  copy:
    src: files/dir.conf
    dest: /etc/apache2/mods-enabled/dir.conf
  notify: restart apache

- name: Copy site config file
  copy:
    src: files/site.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache

- name: Enable configuration
  file:
    src: /etc/apache2/sites-available/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: link
  notify: restart apache
