---
- name: Add ufw rule for ssh
  ufw:
    rule: allow
    port: '22'

- name: Enable ufw
  ufw:
   state: enabled

- name: Install ntp
  apt:
    name: ntp
    state: present
    update_cache: yes
  tags: ntp

- name: Determine if timesyncd is enabled
  register: timesyncdstatus
  command: timedatectl status
  changed_when: false

- name: Disable timesyncd
  command: timedatectl set-ntp off
  when: "'systemd-timesyncd.service active: yes' in timesyncdstatus.stdout"

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp